### ISSUE TITLE
How to parse GET request 

### ISSUE THREAD

**Issue by rragu** [eidheim/Simple-Web-Server#54] opened 2016-05-31 14:00 UTC
Hi,

I'm working on http server, and i want to know how the GET request is been parsed in boost.

Let say, below is the http GET request
http://localhost:8080/match/gt5jjdsc7juty/details?stuId=207&stuGroup=501&maxResults=20

I want to get,

`string a = gt5jjdsc7juty,
string b = details,
int c = 207,
int d = 501,
int e = 20`
Note:
But i can able to fetch integer values as in code. Also i want to get contents which are after &, ?, / and =

Sample Code block 
`server.resource["^/match/([0-9]+)$"]["GET"]=[](HttpServer::Response& response, shared_ptr<HttpServer::Request> request) {
        string number=request->path_match[1];`
Thanks in advance.

**Comment by eidheim** [comment] 2016-05-31 14:05
See #47 Closing as this is a duplicate of #47.

**Closed by eidheim** 2016-05-31 14:05 UTC

**Comment by rragu** [comment] 2016-05-31 15:10
Hi,

Thanks for the quick response.
I got the integer values as said in the comment. 

As i said before i couldn't able to get string value. (i.e. i need to get value after /match/ in the request below.)

http://localhost:8080/match/gt5jjdsc7juty/details?stuId=207&stuGroup=501&maxResults=20
