### ISSUE TITLE
Crash when used alongside boost::propery_tree XML parser.

### ISSUE THREAD

**Issue by bobeff** [eidheim/Simple-Web-Server#59] opened 2016-07-21 20:24 UTC
[Here ](http://stackoverflow.com/questions/37623314/crash-in-boostcoroutine-library-when-used-alongside-boostproperty-tree-xml-p) is the description of the problem. I'm not sure whether this is problem of the _Simple-Web-Server_ or the problem is in some of the used boost libraries.

**Comment by eidheim** [comment] 2016-07-21 22:21
Have you tried with the latest version/master? The implementation now is simpler and has fewer dependencies.

**Comment by eidheim** [comment] 2016-07-22 08:23
Boost.coroutine is no longer a dependency in v2.0.0, so the issue is most likely fixed in the latest version?

**Comment by bobeff** [comment] 2016-07-22 08:26
I tested it with **v2.0** of _Simple-Web-Server_ and my web service no longer crashes. Thank you.

**Comment by eidheim** [comment] 2016-07-22 08:29
Thank you for verifying.

**Closed by eidheim** 2016-07-22 08:29 UTC
